<<<<<<< HEAD
[build]
  functions = "netlify/functions"

  [functions]
=======
functionsDirectory = "C:\\Users\\s2401241\\AIchatbot\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\s2401241\\AIchatbot"
publishOrigin = "default"
functions = "C:\\Users\\s2401241\\AIchatbot\\netlify\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions."*"]
>>>>>>> 8f7f1e1478fe0ee79fa5ac636e00fb55698513e1
  node_bundler = "esbuild"